### ISSUE TITLE
Gilhub

### ISSUE THREAD

**Issue by RyuuseiguN** [bittner/gitter#1]

**Comment by bittner** [comment]
Did you want to ask  a specific question?

**Comment by RyuuseiguN** [comment]
I want to jailbreak ios but I can't downgrade to ios 9.3.3 
Now ios 10.1.1 help me 
Thank you

ส่งจาก iPhone ของฉัน

เมื่อ 10 พ.ย. 2559 เวลา 5:17 AM Peter Bittner notifications@github.com เขียน:

**Comment by bittner** [comment]
@RyuuseiguN This is the wrong planet. Please land your warcraft in another galaxy. You're violating the code of conduct of the Intergalactic Treaty. Yours is abusive behavior.

This incident will be reported.
